# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Luo Zhiyang/OneDrive - National University of Singapore/Y2S2/EE2026/Project/MODS.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img.xci
# IP: The module: 'blk_mem_gen_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luo Zhiyang/OneDrive - National University of Singapore/Y2S2/EE2026/Project/MODS.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_img'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Luo Zhiyang/OneDrive - National University of Singapore/Y2S2/EE2026/Project/MODS.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img.xci
# IP: The module: 'blk_mem_gen_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luo Zhiyang/OneDrive - National University of Singapore/Y2S2/EE2026/Project/MODS.xpr/MODS/MODS.srcs/sources_1/ip/blk_mem_gen_img/blk_mem_gen_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_img'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
